name: user-web
port: 8021
user-srv:
  host: 192.168.44.15
  port: 50051
  name: 'user-srv'

jwt:
  key: 'shenchangxingogogo'

ali-sms:
  key: 'ttttt'
  secret: 'tttttt'

redis:
  host: 192.168.24.5
  port: 6379

consul:
  host: 192.168.44.15
  port: 8500